### ISSUE TITLE
working on set of modified tools can trigger dependency issues.

### ISSUE THREAD

**Issue by lacostej** [fastlane/countdown#15]
I ran into an issue which looked like this
- I have a countdown repo with all fastlane modules checked out.
- I have many local modules patched, some not yet rebased on top of latest master
- I started rebasing some module branches on top of master

I ran into strange dependencies issues such as 

```
lacostej@Jeromes-MacBook-Pro ~/Code/OSS/Fastlane2/countdown/fastlane (upgrade_supply_google_api_client) rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:114:in `require': unable to find a version of 'fastlane_core' to activate (Gem::LoadError)
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/match-0.2.5/lib/match/options.rb:1:in `<top (required)>'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/match-0.2.5/lib/match.rb:2:in `<top (required)>'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/actions/match.rb:43:in `available_options'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/spec/unused_options_spec.rb:7:in `block (4 levels) in <top (required)>'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/documentation/actions_list.rb:137:in `block in all_actions'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/documentation/actions_list.rb:131:in `each'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/documentation/actions_list.rb:131:in `all_actions'
```

This was probably caused by some tools being outdated while the current one requiring newer version. And as countdown modify the gem dependencies to use all countdown local directories, I was stuck.

Running `rake pull` in countdown didn't work (as my projects are locally pointing to branches)

So I basically had to go and pull and rebase all my local branches one by one until it worked again.

Not really sure what to do from there.
- `rake pull` could only pull the ones that are on master, and display a warning for the others.
- better idea ?

**Comment by i2amsam** [comment]
Would a `bundle install` in the branch you were working in fix it?  I'm not sure I fully understand the issue, but it would make sense to me that if multiple modules depend on a common gem that they'll each clobber each other when they bundle install.

**Comment by mfurtak** [comment]
As a follow on, @lacostej In your example, you ran `rspec`... does `bundle exec rspec` do any better?

**Comment by lacostej** [comment]
I tried to run `bundle exec rspec`. The error was then different, and hinted a me having to do a `bundle install`. And after install, both (`rspec` and `bundle exec rspec`) executions worked. Not sure if the issue was exactly the same though. Next time it happens, I'll try again.

Here's the log:

```
lacostej@Jeromes-MacBook-Pro ~/Code/OSS/Fastlane2/countdown/fastlane (pager_less_ci) rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:114:in `require': unable to find a version of 'fastlane_core' to activate (Gem::LoadError)
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/match-0.3.0/lib/match/options.rb:1:in `<top (required)>'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/match-0.3.0/lib/match.rb:2:in `<top (required)>'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /Users/lacostej/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/actions/match.rb:43:in `available_options'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/spec/unused_options_spec.rb:7:in `block (4 levels) in <top (required)>'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/documentation/actions_list.rb:137:in `block in all_actions'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/documentation/actions_list.rb:131:in `each'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/lib/fastlane/documentation/actions_list.rb:131:in `all_actions'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/spec/unused_options_spec.rb:6:in `block (3 levels) in <top (required)>'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `module_exec'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/spec/unused_options_spec.rb:3:in `block (2 levels) in <top (required)>'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `module_exec'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/spec/unused_options_spec.rb:2:in `block in <top (required)>'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `module_exec'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:82:in `block (2 levels) in expose_example_group_alias_globally'
    from /Users/lacostej/Code/OSS/Fastlane2/countdown/fastlane/spec/unused_options_spec.rb:1:in `<top (required)>'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/bin/rspec:23:in `load'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/bin/rspec:23:in `<main>'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
    from /Users/lacostej/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
lacostej@Jeromes-MacBook-Pro ~/Code/OSS/Fastlane2/countdown/fastlane (pager_less_ci) bundle exec rspec
Could not find gem 'rest-client (~> 1.6.7)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
```

**Comment by KrauseFx** [comment]
Closing this now, as it's fixed with mono gem I think 👍
